export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: '/auth/login',
    REGISTER: '/auth/register',
    REFRESH: '/auth/refresh',
    LOGOUT: '/auth/logout',
    ME: '/auth/me',
  },
  PRODUCTS: {
    LIST: '/products',
    DETAIL: (id: string) => `/products/${id}`,
    BY_SLUG: (slug: string) => `/products/slug/${slug}`,
    SPECS: (id: string) => `/products/${id}/specs`,
  },
  CATEGORIES: {
    LIST: '/categories',
    DETAIL: (id: string) => `/categories/${id}`,
    SPECS_TEMPLATE: (slug: string) => `/categories/${slug}/specs-template`,
  },
  BUILDS: {
    LIST: '/builds',
    CREATE: '/builds',
    DETAIL: (id: string) => `/builds/${id}`,
    UPDATE: (id: string) => `/builds/${id}`,
    DELETE: (id: string) => `/builds/${id}`,
    ITEMS: (buildId: string) => `/builds/${buildId}/items`,
    ITEM_DETAIL: (buildId: string, itemId: string) => `/builds/${buildId}/items/${itemId}`,
    SAVE: (id: string) => `/builds/${id}/save`,
    VERSIONS: (id: string) => `/builds/${id}/versions`,
    VERSION_DETAIL: (id: string, versionId: string) => `/builds/${id}/versions/${versionId}`,
    DUPLICATE: (id: string) => `/builds/${id}/duplicate`,
    PUBLISH: (id: string) => `/builds/${id}/publish`,
    UNPUBLISH: (id: string) => `/builds/${id}/unpublish`,
    SHARE: (shareUrl: string) => `/builds/share/${shareUrl}`,
    CHECK_COMPATIBILITY: '/builds/check-compatibility',
    EVALUATE: '/builds/evaluate',
  },
  ORDERS: {
    LIST: '/orders',
    MY_ORDERS: '/orders/my-orders',
    CREATE: '/orders',
    DETAIL: (id: string) => `/orders/${id}`,
  },
  BRANDS: {
    LIST: '/brands',
    DETAIL: (id: string) => `/brands/${id}`,
    BY_SLUG: (slug: string) => `/brands/slug/${slug}`,
  },
  REVIEWS: {
    BY_PRODUCT: (productId: string) => `/reviews/product/${productId}`,
    CREATE: '/reviews',
    DETAIL: (id: string) => `/reviews/${id}`,
  },
  WISHLIST: {
    GET: '/wishlist',
    ADD_ITEM: '/wishlist/items',
    REMOVE_ITEM: (itemId: string) => `/wishlist/items/${itemId}`,
  },
  COMPARE: {
    PRODUCTS: (ids: string[]) => `/products/compare?ids=${ids.join(',')}`,
  },
  CONFIGURATOR: {
    USE_CASES: '/configurator/use-cases',
    BASE_BUILDS: '/configurator/base-builds',
    BASE_BUILD_DETAIL: (id: string) => `/configurator/base-builds/${id}`,
    BASE_BUILD_OPTIONS: (id: string) => `/configurator/base-builds/${id}/options`,
  },
  COMMUNITY: {
    BUILDS: '/community/builds',
    FILTERS: '/community/builds/filters',
    BY_SLUG: (slug: string) => `/community/builds/${slug}`,
    LIKE: (id: string) => `/community/builds/${id}/like`,
    COMMENTS: (id: string) => `/community/builds/${id}/comments`,
    REPORT: (id: string) => `/community/builds/${id}/report`,
    PUBLISH: '/community/builds',
  },
} as const;
